### ISSUE TITLE
autoclicker.py doesnt work

### ISSUE THREAD

**Issue by TechItAllSA** [TechItAllServices/miscellaneous-code#1]
I'm not sure if its because I tested it on a Chromebook without Linux or if it just doesn't work at all. I recommend using 'pyautogiu' instead if 'pynut' (py input).

**Comment by purpleguy5728** [comment]
fixed

**Comment by TechItAllSA** [comment]
It's not fixed...in fact, you just have imports and one variable. There is no code to even run it in the first place!
